SysBioChalmers/GECKO

- geckomat/change_model/manualModifications.m
- geckomat/get_enzyme_data/findInDB.m
- geckomat/get_enzyme_data/flattenCell.m
- geckomat/get_enzyme_data/getEnzymeCodes.m
- refactor:
- `manualModifications` speed improvement
- `findInDb` and `getEnzymeCodes` speed improvement
> refactor: speed-up functions

- geckomat/limit_proteins/constrainEnzymes.m
detected some bugs when calling `measureAbundance` from within `constrainEnzymes`.
> fix: constrainEnzymes

- geckomat/utilities/getSubset_ecModel.m
Function that gets a context-specific model and a general ecModel, it maps each of the metabolic reactions in the model on the general ecModel and gets all the necessary components for the creation of a context-specific ecModel.
> feat: added getSubset_ecModel

- geckopy/tests/test_gecko.py
pd.Series.from_csv was deprecated for python 3.x
> fix: update csv reader in geckopy test

- .gitignore
- geckopy/geckopy/data.py
This due to cobrapy updating to handle differently square brackets. Also, (git)ignore pycharm files.
> fix: met id parsing in geckopy

- .travis.yml
- README.rst
- geckopy/tox.ini
pandas 1.0 is only supported for python 3.6+
> fix: update envlist in CI

- geckomat/change_model/convertToEnzymeModel.m
- geckomat/change_model/manualModifications.m
- geckomat/change_model/preprocessModel.m
- geckomat/change_model/removeIncorrectPathways.m
- geckomat/enhanceGEM.m
- geckomat/get_enzyme_data/getEnzymeCodes.m
- geckomat/get_enzyme_data/matchKcats.m
- geckomat/kcat_sensitivity_analysis/modifyKcats.m
- geckomat/kcat_sensitivity_analysis/sigmaFitter.m
- geckomat/limit_proteins/constrainEnzymes.m
- geckomat/limit_proteins/fitGAM.m
- geckomat/limit_proteins/getConstrainedModel.m
- geckomat/limit_proteins/measureAbundance.m
- models/ecYeastGEM/ecYeastGEM_exchangeFluxes.txt
- models/saveECmodel.m
Following #123, I have adapted the GECKO pipeline to show a more concise log, see below for our use case of `ecYeast8.1.3`.
@IVANDOMENZAIN @mihai-sysbio I will proceed with generating an exchange flux file (as discussed with @IVANDOMENZAIN), but in the meantime let me know if this log is manageable for ecModels, or if we should continue to reduce it even more.
```matlab
***************************************************************
GECKO: Adding enzyme constraints to a genome-scale model
***************************************************************
Getting genome-scale model ready... Done!
==================
Generating ecModel:
==================
Retrieving EC numbers....................................... Done!
Matching kcats....................................... Done!
Adding enzymes …
```
> style: adapt Matlab log

- src/geckomat/change_model/applyKcatConstraints.m
- src/geckomat/change_model/makeEcModel.m
- src/geckomat/gather_kcats/runDLKcat.m
- src/geckomat/kcat_sensitivity_analysis/sensitivityTuning.m
Solution of error caused by `movefile`, since it need to be in the `dlkcat` folder.
@edkerk: also speed improvement of sensitivityTuning and makeEcModel warning if model is not in RAVEN format.
> fix: change the dir after moving DLKcat output file

- src/geckomat/kcat_sensitivity_analysis/Bayesian/bayesianSensitivityTuning.m
- src/geckomat/model_adapter/ModelAdapter.m
- test/unit_tests/ecTestGEM/TestGEMAdapter.m
- tutorials/protocol.m
- userData/ecHumanGEM/HumanGEMAdapter.m
- userData/ecYeastGEM/YeastGEMAdapter.m
- userData/yourModel/yourModelAdapter.m
> fix: updated protocol to adapt to changes in findMetSmiles

- src/geckomat/change_model/makeEcModel.m
- src/geckomat/gather_kcats/writeDLKcatInput.m
- test/manual_tests/TestHumanGEMSimpleWorkflow.m
- test/manual_tests/TestYeastGEMSimpleWorkflow.m
> Johan fixes1

- src/geckomat/change_model/findMetSmiles.m
- src/geckomat/limit_proteins/fillProtConcs.m
- feat:
- `findMetSmiles` appends to output file as soon as query results arrive, possibly solves #239 
> feat: findMetSmiles intermediate output

- src/geckomat/change_model/applyComplexData.m
Solves #249 
Tested with data provided in #249, comments:
https://github.com/SysBioChalmers/GECKO/issues/249#issue-1603338884
https://github.com/SysBioChalmers/GECKO/issues/249#issuecomment-1448623950
> Fix: error calculating the match percentage

- src/geckomat/change_model/applyCustomKcats.m
This PR resolves #255 and slightly improves the error messages.
> fix: check for customkcats file resolves #255

- src/geckomat/change_model/applyComplexData.m
- src/geckomat/change_model/applyCustomKcats.m
- src/geckomat/gather_kcats/getStandardKcat.m
- Solution for #258 
- Remove draft line in applyCustomKcats
> feat/fix: getStandardKcat in model without subSystems - other minor bugs

- src/geckomat/change_model/applyComplexData.m
- src/geckomat/change_model/applyCustomKcats.m
- src/geckomat/change_model/makeEcModel.m
- src/geckomat/change_model/setProtPoolSize.m
- src/geckomat/gather_kcats/getStandardKcat.m
- src/geckomat/kcat_sensitivity_analysis/sensitivityTuning.m
- src/geckomat/limit_proteins/constrainProtConcs.m
- src/geckomat/limit_proteins/flexibilizeProtConcs.m
- src/geckomat/limit_proteins/getConcControlCoeffs.m
- src/geckomat/limit_proteins/updateProtPool.m
- src/geckomat/utilities/enzymeUsage.m
- test/unit_tests/geckoCoreFunctionTests.m
- test/unit_tests/getBaseExpTstEcModelProperties.m
- Swap protein usage reaction to be negative numbers 
(This branch contains the changes in PR #261)
> Swap protein usage

- README.rst
> Edkerk patch 1

- protocol.m
This reverts commit ae7c7a1da7d614cb8b922592dfc4ea1354bd2e88.
- fix: inadvertently deleted the wrong copy of `protocol.m`
> Revert "chore: remove old files"

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug-detected.md
- .github/ISSUE_TEMPLATE/new-feature.md
- .github/pull_request_template.md
- doc: update PR and Issues templates with new branch names and reduce number of requested input to the most meaningful
- doc: update `CONTRIBUTING.md` to reflect recent changes
> doc: PR and Issues templates + contributing guidelines

- src/geckomat/get_enzyme_data/getECfromDatabase.m
- fix:
- `getECfromDatabase` only change ecRxns entries (solves #281)
> fix: getECfromDatabase only change ecRxns entries

- src/geckomat/change_model/applyCustomKcats.m
- test/unit_tests/ecTestGEM/data/customKcats.tsv
- test/unit_tests/geckoCoreFunctionTests.m
- fix
- `applyCustomKcats` should be able to directly take a customKcat structure as input (solves #303)
> fix: applyCustomKcats with customKcats structure input

- doc/src/geckomat/change_model/applyComplexData.html
- src/geckomat/change_model/applyComplexData.m
- refactor:
- `applyComplexData` 291x speed improvement (0.78 sec instead of 226 sec in _full_ecModel_ tutorial).
> refactor: applyComplexData

- tutorials/full_ecModel/protocol.m
- tutorials/light_ecModel/protocol.m
This PR is used to highlight a few places where the tutorials can be further improved/simplified. Please feel free to push commits to this branch.
> docs: futher polishing

- README.md
- tutorials/full_ecModel/protocol.m
- tutorials/light_ecModel/protocol.m
This PR adds the DOI to the places where it was already meant to be added: readme and 2 code files.
> chore: update-doi

- doc/src/geckomat/gather_kcats/getStandardKcat.html
- doc/src/geckomat/utilities/getSubsetEcModel.html
- src/geckomat/gather_kcats/getStandardKcat.m
- src/geckomat/utilities/getSubsetEcModel.m
- Fixes:
- `getStandardKcat` defines compartment of standard protein (solves #404)
- `getSubsetEcModel` accepts also full_ecModels and 'prot_standard' (solves #405)
> GECKO 3.2.4
