SysBioChalmers/GECKO

.travis.yml

Unless you insist to have them this PR suggests to remove the Mac builds. They are currently extremely slow on Travis because they have so few Mac machines for so many testers.

fix: remove mac builds, improve conditions

---

.travis.yml

* pandas dropped support for Python 3.4.

fix: remove 3.4 environment

---

Matlab_Module/Kcat_sensitivity_analysis/modifyKcats.m
Matlab_Module/Kcat_sensitivity_analysis/topUsedEnzymes.m
Matlab_Module/Kcat_sensitivity_analysis/truncateValues.m
Models/saveECmodelSBML.m

* Numbers in scientific notation are stored in the `.xml` files with format `5e-03`, not `5e-003`, regardless of the OS used for generating them.
* Numbers in all other result files (`kcatModifications.txt`, `topUsedEnzymes.txt`, etc.) are shown with up to 6 significant figures.

Fix/inter OS issues

---

geckomat/kcat_sensitivity_analysis/modifyKcats.m
geckomat/kcat_sensitivity_analysis/topUsedEnzymes.m
geckomat/kcat_sensitivity_analysis/truncateValues.m
geckomat/limit_proteins/getConstrainedModel.m

- doc:
- explanation of input parameters
- refactor:
- `topUsedEnzymes`only generate table from cell array near end of function, for speed improvement and getting rid of warnings when new data was added to the table
- feat:
- `topUsedEnzymes` optional parameters: `writeFile` and `n` for number of top used enzymes, and now supporting `T` as command line output
- `topUsedEnzymes` output table now contains additional column specifying the condition, this changes the output from before this commit
- `truncateValues` directly uses column numbers: instead of `nCols` referring to last number of columns, `cols` now contains directly which columns should have their value truncated.
- fix:
- `modifyKcats` supports new `truncateValues` behaviour

refactor/feat: topUsedEnzymes, truncateValues and modifyKcats

---

geckomat/utilities/getKcat.m

This PR addresses #73 reported by @johanbj. Thanks for your contribution!

fix: correct typos in getKcat utilities function

---

README.rst

GECKO makes extensive use of the `contains` function in MATLAB, which was introduced in the 9.1 (R2016b) version. Documentation has been updated accordingly.

doc: update required MATLAB version in README file

---

geckomat/limit_proteins/flexibilizeProteins.m

I encountered the following case:
1. `flexibilizeProteins` releases the UB of 13 proteins. Protein X is the 8th protein flexibilized.
2. When `getNewBounds` is run as part of `flexibilizeProteins`, the flux through prot_X_exchange is *lower* than the measured abundance. It seems that flexibilization of proteins 9-13 _after_ protein X make protein X no longer limiting the growth.
3. `getNewBounds` then sets the UB of flexibilized proteins to the value that is reached when the completely flexibilized model is simulated. In the case of protein X, this value is lower than the measured abundance, but the UB is still set to this value.
4. While this would not be desired (discarding the measured abundance even when not required), by itself it does not cause any problem (the model should still …

fix: change UB only if flexibilized > measured

---

geckomat/enhanceGEM.m
geckomat/kcat_sensitivity_analysis/modifyKcats.m

The storage of `ecModel` output files used to rely on a previously existing destination folder.  In the case of `ecYeastGEM`, a destination folder already exists in the `GECKO` repository, but for newly added cases with a different model name this causes  an error. 
This issue has been partially addressed in #80 by the creation of the subfolder `GECKO/models/name` for any new case with a given ecModel name. However, this bug fix introduced the creation of such subfolder in the first potential saving step, within the function `modifyKcats.m`, which is just called for the iterative kcat curation procedure for overconstrained ecModels. In the case of generated ecModels that are able to reach the provided experimental growth rate without the need of kcats curation the first saving step takes …

fix: create folder for ecModel files

---

README.rst
geckopy/travis_pypi_setup.py

After #116, the CI suite is now operating at https://travis-ci.com/github/SysBioChalmers/GECKO, so a few changes in the repo were needed to point to the new address.

chore: migrate to travis-ci.com

---

geckomat/limit_proteins/measureAbundance.m

Allow processing of empty `prot_abundance.txt` files by the `limit_proteins/measureAbundance.m` function, which should return a default **`f=0.5`** value in this case. 
This intends to facilitate the generalization of the automated [ecModels update](https://github.com/MetabolicAtlas/ecModels) by GitHub actions. This issue was pointed out in this [discussion](https://github.com/SysBioChalmers/ecModels/issues/19#issuecomment-748471479).

fix: allow empty prot_abundance.txt files

---

geckomat/utilities/getSubset_ecModel.m

A few changes were made to the `getSubset_ecModel` function to make sure that it runs as expected. I've summarized the changes below with some explanations.
**Function header**: 1b9534b
I just noticed some of the variable names hadn't been updated in the function header, so I corrected those.
**Use default UB**: 11b53a5
I often use a default upper/lower bound of `+/-Inf` rather than `+/-1000` when working with ecGEMs due to numerical solver issues. The function now uses the value from `.annotation.defaultUB` if the field exists in the ecGEM structure.
**Perform exact pattern matching for reactions**: 5c0f5c7; refactored: 6dd91f0
Previously, the code was searching for ecGEM reactions whose names contained any of the `smallGEM` reactions. For example, for `smallGEM` reaction `HMR_1000`, it …

Fix/updates to getSubset_ecModel

---

geckomat/change_model/makeEcModel.m

In contrast to #166, incorporating the new structure from: https://github.com/SysBioChalmers/GECKO/issues/156#issuecomment-1174441460.
Most considerate changes:
- One `model.ec` kcat entry per reaction
- So no duplicate entries for alternative substrates
- No duplicate entries for each subunit of a complex
- Number of subunit copies indicated in new `rxnEnzMat` sparse matrix
- `geckoLight` flag to prepare for GECKO light model formulation (= no splitting of reactions with isoenzymes)

feat: simplified model.ec structure

---

GECKOInstaller.m
geckomat/model_adapter/HumanGEMAdapter.m
geckomat/model_adapter/ModelAdapter.m
geckomat/model_adapter/YeastGEMAdapter.m
geckomat/model_adapter/getHumanGEMRootPath.m

Added an adapter pattern that can enable us to use GECKO for different species without copying files. Right now the adapter is pretty small, but the idea is to add more functions in the base class when needed. The idea is then that an adapter is sent into GECKO when generating models, and that GECKO can ask the adapter for information that is accessed differently for each species/model. Examples include parameters, pathways to data, and which reactions are spontaneous. The code is not plugged in anywhere, so this is totally safe.
I also added an installation script, let's see what you think about that. To install (i.e., setup path): 
cd to GECKO root
GECKOInstaller.install
to uninstall (i.e., remove GECKO from path):
GECKOInstaller.uninstall
This is practical if you have several versions …

feat: ModelAdapter pattern for organism specific parameters and customizations

---

geckomat/change_model/applyKcatConstraints.m
geckomat/change_model/makeEcModel.m

As suggested by @Yu-sysbio, to resolve low fluxes (#147) and have a model formulation that is coherent across full and light GECKO versions, the enzyme usage coefficients are defined as MW/kcat, where MW is given in Dalton (and not kDa).

fix: use MW/kcat instead of 1/kcat

---

src/geckomat/change_model/makeEcModel.m

1. When making a new ec-model, currently all reversible reactions are made irreversible.
2. The reason for making irreversible is to avoid negative enzyme usage (or in other words: enzyme pseudometabolites being produced instead of consumed).
3. Only reactions that will be extended with enzyme constraints need to be made irreversible, other reactions (e.g. exchange) do not.
4. Making reactions unnecessarily irreversible results in a larger model with numerous loops.
Therefore, the code here only makes reactions reversible if they are associated to a gene.
Note, #193 should be merged to `devel3` first, after which this PR should be based on `devel3`.

feat: skip making exchange rxns reversible

---

src/geckomat/gather_kcats/getStandardKcat.m
userData/ecHumanGEM/HumanGEMAdapter.m
userData/ecYeastGEM/YeastGEMAdapter.m
userData/yourModel/yourModelAdapter.m

A standard kcat value is calculate for those reactions with missing GPR, except transport, spontaneous, exchange, and pseduoreactions.
A standard Kcat is defined for all the rxns which does not have a GPR rule defined. In this case, the kcat value for a particular reaction is defined as the mean of the kcat values of the reactions involved in the same subsystem in which the given reaction is involved. Nevertheless, if a subSystem have a number of reactions lower than a treshold, the kcat value will be the median of the kcat in all the reactions of the model.
Additionally, an stardard MW is defined for all the rxns which does not have a GPR rule defined. This is based in all the proteins reported for the specific organism in uniprot
A pseudometabolite named 'prot_standard' will be added as …

Feat: calculate a standard kcat value for missing GPR reactions

---

src/geckomat/gather_kcats/getStandardKcat.m

Add standard kcats in light version models. 

Feat: add standard kcats in light version

---

src/geckomat/gather_kcats/runDLKcat.m
src/geckomat/gather_kcats/runDLKcatFromDocker.m

- Uses a Docker image to run DLKcat in cases `runDLKcat` fails. I test it on my computer so, It would be great if several of you could test it on other computers (MacOS, Windows, and different architecture).
Download the DLKcat can take some time depending of course of the internet speed. It is around 1.9 GB
Docker desktop can be dowloaded from "https://www.docker.com". When running DLKcat docker CLI needs Docker desktop running.

feat: run DLKcat from a Docker image

---

src/geckomat/limit_proteins/constrainFluxData.m
src/geckomat/limit_proteins/flexibilizeProtConcs.m

When there are multiple conditions in proteomics integration, only one condition to `setParam` should be selected.

Fix: constraint flux exchange of a specific condition

---

src/geckomat/get_enzyme_data/getECfromDatabase.m

- fix: `getECfromDatabase` incorrect definition of `ecRxns` and `action` input parameters

fix: getECfromDatabase incorrect input definition

---

protocol.m
src/geckomat/change_model/applyKcatConstraints.m
src/geckomat/gather_kcats/readDLKcatOutput.m

- fix:
- check whether `runDLKcat` was run on `DLKcat.tsv` (solves #278)
- filter out any non-numeric kcat value in `DLKcat.tsv`

fix: read runDLKcat output

---

src/geckomat/change_model/applyCustomKcats.m
src/geckomat/change_model/applyKcatConstraints.m

Fix bug where if any reaction does not match with data in customKcats cause and error. Reported in #291  

fix: error if any match in customKcats

---

src/geckomat/gather_kcats/fuzzyKcatMatching.m

- fix:
- `fuzzyKcatMatching` solves #277 when KEGG has multiple entries with the same organism name.  

fix: if organism is in KEGG multiple times

---

protocol.m
src/geckomat/gather_kcats/fuzzyKcatMatching.m
src/geckomat/gather_kcats/getStandardKcat.m

- fix: minor issues raised in #288, #289

fix: minor issues raised

---

src/geckomat/gather_kcats/getStandardKcat.m

- fix:
- `getStandardKcat` handling models that have multiple subSystems assigned to the same reaction.

fix: getStandardKcat with multiple subSystems

---

src/geckomat/kcat_sensitivity_analysis/sensitivityTuning.m

- User can define a list of protein which will not be considered in `sensitivityTuning`. 
- Solves #294 
- Tested with both full and light ecModels in yeast following the `protocol.m`

Feat: ignore in tunning kcats user defined proteins

---

src/geckomat/model_adapter/adapterTemplate.m
src/geckomat/utilities/startGECKOproject.m

- Propose a function that create the basic GECKO 3 project structure. Instead of copy and paste `yourModel` folder, user can use `startGECKOproject()` that creates a new folder with the `{code, data, models, output}` structure required. Moreover it write a basic adapter class that can be more user friendly to adjust. 
- For now, this is a proposal, in case is accepted, `yourModel` folder will be removed and protocol needs update. 
- This branch was created using develop as base branch

feat: a function that creates a the project structure an adapter class

---

src/geckomat/change_model/makeEcModel.m
src/geckomat/gather_kcats/writeDLKcatInput.m

Based on reviewer's comments:
- feat:
- `makeEcModel` can use pseudoRxns.tsv to identify pseudoreactions
- `writeDLKcatInput` only exclude currency metabolites if there are other reactants involved in the reaction

feat: currencyMets and pseudoreactions handling

---

src/geckomat/change_model/applyKcatConstraints.m
src/geckomat/gather_kcats/getStandardKcat.m
src/geckomat/get_enzyme_data/copyECtoGEM.m

- fix:
- `getStandardKcat` failed to add constraints after `applyKcatConstraints` due to missing `rxnEnzMat` entries
- refactor:
- `applyKcatConstraints` faster on light ecModels by avoiding for-loops
- `getStandardKcat` faster by avoiding for-loops and findgroups
- feat:
- `copyECtoGEM` function to copy `ecModel.ec.eccodes` to `ecModel.eccodes` (reviewer request)

fix: getStandardKcat and applyKcatConstraints

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug-detected.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/new-feature.md
.github/pull_request_template.md

- Documentation:
- Clarify PR merging strategies to `develop` (squash-merge) and `main` (merge commit) in _Contributor guidelines_.
- Change PR template to nudge towards using the correct PR merging strategy.
- Instruct in _Contributor guidelines_ to increment `version.txt` with each release.

doc: clarify PR merge strategies in contrib guide

---

doc/src/geckomat/utilities/ecFSEOF.html
doc/src/geckomat/utilities/getFluxTarget.html
src/geckomat/utilities/ecFSEOF.m
src/geckomat/utilities/getFluxTarget.m

- fix error when getting max flux target.  Protein pool minimization is done after fixing growth rate. Then resulted pool usage is fixed. Finally, target is set as objetive for minimize (if output is defined) and maximize. 
- some unnecessary input in `getFluxTarget` were removed
- fix alpha for WT to be 100%. 

Fix: get flux target at different alphas

---

doc/src/geckomat/get_enzyme_data/loadDatabases.html
src/geckomat/get_enzyme_data/loadDatabases.m

- Fixes:
- `loadDatabases` throws error if duplicate protein IDs are found

fix: loadDatabases check for duplicate protIDs

---

doc/src/geckomat/limit_proteins/calculateFfactor.html
src/geckomat/limit_proteins/calculateFfactor.m

- Fixes:
- 'calculateFfactor` handle data from PAXdb if the taxonomic ID is not 4 digits long (solves #345)

fix: calculateFfactor if paxDB has taxID !4 digits

---

doc/src/geckomat/gather_kcats/runDLKcat.html
src/geckomat/gather_kcats/runDLKcat.m

- Fixes:
- `runDLKcat` correctly handles `param.path` if the folder name has spaces (solves #351)

fix: runDLKcat if path has spaces

---

src/geckomat/utilities/saveEcModel.m
tutorials/light_ecModel/protocol.m

This PR aims to resolve a bug where `.xml` was unnecessarily appended to a filename that already ended with `.xml` when saving an EC model. Also, a typo has been also fixed.

fix: save ec model xml

---

src/geckomat/gather_kcats/runDLKcat.m

It has happened to me that Docker was not detected since Matlab was started from the launcher. However, this detail is mentioned only as a code comment instead as part of the error message.
In this tiny PR I am increasing the visibility of the error details so that the user can be more informed without having to dig through the code.

feat: clearer mac docker error

---

GECKOInstaller.m
doc/src/geckomat/limit_proteins/flexibilizeEnzConcs.html
src/geckomat/limit_proteins/flexibilizeEnzConcs.m

- Fixes:
- `flexibilizeEnzConcs` could mix-up new lower bounds of flexibilized proteins.
- `GECKOInstaller` correctly identify if existing GECKO version should be updated.

fix: flexibilizeEnzConcs mix up flexibilized proteins

---

doc/src/geckomat/gather_kcats/getStandardKcat.html
src/geckomat/gather_kcats/getStandardKcat.m

- Fixes:
- `getStandardKcat` should use enzyme_comp specified in the modelAdapter, and not a hard-coded 'c' (solves #400)

fix: getStandardKcat use modelAdapter enzyme_comp

---

GECKOInstaller.m
doc/src/geckomat/gather_kcats/getStandardKcat.html
doc/src/geckomat/limit_proteins/flexibilizeEnzConcs.html
src/geckomat/gather_kcats/getStandardKcat.m
src/geckomat/limit_proteins/flexibilizeEnzConcs.m

- Fixes:
- `flexibilizeEnzConcs` could mix-up new lower bounds of flexibilized proteins.
- `GECKOInstaller` correctly identify if existing GECKO version should be updated.
- `getStandardKcat` should use enzyme_comp specified in the modelAdapter, and not a hard-coded 'c' (solves #400)

GECKO 3.2.3

---

doc/src/geckomat/gather_kcats/getStandardKcat.html
doc/src/geckomat/utilities/getSubsetEcModel.html
src/geckomat/gather_kcats/getStandardKcat.m
src/geckomat/utilities/getSubsetEcModel.m

- Fixes:
- `getStandardKcat` defines compartment of standard protein (solves #404)
- `getSubsetEcModel` accepts also full_ecModels and 'prot_standard' (solves #405)

fix: prot_standard related bugs
